package com.baby.babyproject.module.dao.mapper;

import com.baby.babyproject.module.dao.entity.BabyProjectLog;
import com.baby.babyproject.module.dao.entity.BabyProjectLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BabyProjectLogMapper {
    long countByExample(BabyProjectLogExample example);

    int deleteByExample(BabyProjectLogExample example);

    int deleteByPrimaryKey(String id);

    int insert(BabyProjectLog record);

    int insertSelective(BabyProjectLog record);

    List<BabyProjectLog> selectByExampleWithBLOBs(BabyProjectLogExample example);

    List<BabyProjectLog> selectByExample(BabyProjectLogExample example);

    BabyProjectLog selectByPrimaryKey(String id);

    int updateByExampleSelective(@Param("record") BabyProjectLog record, @Param("example") BabyProjectLogExample example);

    int updateByExampleWithBLOBs(@Param("record") BabyProjectLog record, @Param("example") BabyProjectLogExample example);

    int updateByExample(@Param("record") BabyProjectLog record, @Param("example") BabyProjectLogExample example);

    int updateByPrimaryKeySelective(BabyProjectLog record);

    int updateByPrimaryKeyWithBLOBs(BabyProjectLog record);

    int updateByPrimaryKey(BabyProjectLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baby_project_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BabyProjectLog selectOneByExample(BabyProjectLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baby_project_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BabyProjectLog selectOneByExampleWithBLOBs(BabyProjectLogExample example);
}