package com.baby.babyproject.module.dao.mapper;

import com.baby.babyproject.module.dao.entity.BabyNames;
import com.baby.babyproject.module.dao.entity.BabyNamesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BabyNamesMapper {
    long countByExample(BabyNamesExample example);

    int deleteByExample(BabyNamesExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(BabyNames record);

    int insertSelective(BabyNames record);

    List<BabyNames> selectByExample(BabyNamesExample example);

    BabyNames selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") BabyNames record, @Param("example") BabyNamesExample example);

    int updateByExample(@Param("record") BabyNames record, @Param("example") BabyNamesExample example);

    int updateByPrimaryKeySelective(BabyNames record);

    int updateByPrimaryKey(BabyNames record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baby_names
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BabyNames selectOneByExample(BabyNamesExample example);
}