package com.baby.babyproject.module.dao.mapper;

import com.baby.babyproject.module.dao.entity.KafkaFailCache;
import com.baby.babyproject.module.dao.entity.KafkaFailCacheExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KafkaFailCacheMapper {
    long countByExample(KafkaFailCacheExample example);

    int deleteByExample(KafkaFailCacheExample example);

    int deleteByPrimaryKey(String id);

    int insert(KafkaFailCache record);

    int insertSelective(KafkaFailCache record);

    List<KafkaFailCache> selectByExampleWithBLOBs(KafkaFailCacheExample example);

    List<KafkaFailCache> selectByExample(KafkaFailCacheExample example);

    KafkaFailCache selectByPrimaryKey(String id);

    int updateByExampleSelective(@Param("record") KafkaFailCache record, @Param("example") KafkaFailCacheExample example);

    int updateByExampleWithBLOBs(@Param("record") KafkaFailCache record, @Param("example") KafkaFailCacheExample example);

    int updateByExample(@Param("record") KafkaFailCache record, @Param("example") KafkaFailCacheExample example);

    int updateByPrimaryKeySelective(KafkaFailCache record);

    int updateByPrimaryKeyWithBLOBs(KafkaFailCache record);

    int updateByPrimaryKey(KafkaFailCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kafka_fail_cache
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    KafkaFailCache selectOneByExample(KafkaFailCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kafka_fail_cache
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    KafkaFailCache selectOneByExampleWithBLOBs(KafkaFailCacheExample example);
}